[package]
name = "blockchain"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
ethers.workspace = true
serde.workspace = true
tracing.workspace = true
thiserror.workspace = true
async-trait = "0.1.89"
