[package]
name = "local_network"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread", "time", "fs"] }
serde_json = "1.0.149"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.23"
alloy = { version = "1.4.3", default-features = false, features = [
    "std",
    "contract",
    "providers",
    "provider-http",
    "reqwest",
    "signer-local",
    "sol-types",
] }
libp2p = { version = "0.56.0" }
clap = "4.5.54"
