[package]
name = "scripts"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.32.0", features = ["full"]}
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
clap = "4.4.5"
ethers = "2.0.10"
