[package]
name = "dkg-peer-registry"
version = "0.1.0"
rust-version = "1.92.0"
edition = "2024"

[dependencies]
dashmap = "6.1.0"
dkg-domain = { path = "../dkg-domain" }
dkg-network = { path = "../dkg-network" }

[lints]
workspace = true
